### ISSUE TITLE
Unable to add urls

### ISSUE THREAD

**Issue by emporeso2** [Nepochal/wallabag-cli#3]
Get this error since yesterday:
`
Traceback (most recent call last):
  File "wallabag.py", line 134, in <module>
    wallabag_add.add(url, title, star, read, quiet)
  File "wallabag_add.py", line 33, in add
    request = api.api_entry_exists(target_url)
  File "api.py", line 283, in api_entry_exists
    header = __get_authorization_header()
  File "api.py", line 126, in __get_authorization_header
    success, token_or_error = get_token()
  File "api.py", line 372, in get_token
    content = json.loads(response.response)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by emporeso2** [comment]
Sorry for the noise , i have a bad ~/.wallabag-cli
